"""Add table and upd table 2

Revision ID: 29098ddc1803
Revises: 
Create Date: 2022-02-19 15:01:43.237330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29098ddc1803'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies_recommended',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommended', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sqlite_autoincrement=True
    )
    op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('movies_recommended')
    # ### end Alembic commands ###
