"""Add slug in MoviesModel

Revision ID: e0c122500f01
Revises: 2bb7cef25d1d
Create Date: 2022-02-13 20:12:59.123634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c122500f01'
down_revision = '2bb7cef25d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'slug')
    # ### end Alembic commands ###
